#!/bin/sh
# File generated by ocamlbuild

cd '/Users/andrew/Documents/Cornell 2015-6/CS3110/CamlDB'

rm -f parser.mli
# Also clean the script itself
rm -f '/Users/andrew/Documents/Cornell 2015-6/CS3110/CamlDB/_build/sanitize.sh'
